### ISSUE TITLE
[DOCUMENT validation] Language issue

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#726]
**Describe the bug**
Je viens de modifier des documents et au moment de la validation celle-ci est impossible et j'ai un message d'erreur
![image](https://user-images.githubusercontent.com/1165144/157604832-e3811d7b-f2d4-43fe-859b-3e90e1e67dd6.png)

Quand je demande à éditer les documents depuis le tableau de validation, en commençant par le premier, le document parent a pour valeur NULL
Si je mets le bon document parent dans le premier fichier et que je le valide, une vingtaine de fichiers disparaissent du tableau mais ils ne sont pas validés. Il en reste 5 à valider. Dans cette liste se retrouve également des documents avec un document parent NULL. Je le laisse ainsi pour que des tests soient possibles

Un document qui n'est plus dans la liste à valider mais qui ne l'a pas été
https://beta.grottocenter.org/ui/documents/135299

**Comment by Clm-Roig** [comment]
> Quand je demande à éditer les documents depuis le tableau de validation, en commençant par le premier, le document parent a pour valeur NULL 

Problème connu, cf #721 (je te confirme que le parent est bien présent dans ce document, ça ne cause pas de problème de validation en soit : c'est juste un manque d'info à afficher).

Je cherche pour le reste...

**Comment by Clm-Roig** [comment]
ça vient de la langue du document, cf message d'erreur : 

`
  "message": "Cannot perform update with the provided values.\nDetails:\n  Could not use specified `language`.  Expecting an id representing the associated record, or `null` to indicate there will be no associated record.  But the specified value is not a valid `language`.  Instead of a string (the expected pk type), the provided value is: { id: 'por' }\n"
`
On utilise un objet ({id: 'po'}) au lieu de simplement utiliser "por".
